version: "3.8"

services:
  api:
    build: ./
    ports:
      - 3001:3001
    environment:
      MONGO_URI: mongodb://db/qquote
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - qquote:/data/db

volumes:
  qquote: 
